### PR TITLE
This closes #65

### LINKED ISSUE #65: Confusion on the usage of "MODE", "ASYNC_MODE" and "mode" in docs
**1. Missing "MODE" in the example configuration file**
Using the `configuration.json` file provided in [h5bench.readthedocs.io](https://h5bench.readthedocs.io/en/latest/running.html#benchmarks) returns the following error:

```shell
2022-08-02 11:47:13,410 h5bench - INFO - Starting h5bench Suite
2022-08-02 11:47:13,410 h5bench - WARNING - Base directory already exists: output
2022-08-02 11:47:13,410 h5bench - INFO - Lustre support not detected
2022-08-02 11:47:13,410 h5bench - INFO - h5bench [write] - Starting
2022-08-02 11:47:13,410 h5bench - INFO - h5bench [write] - DIR: output/c9a31822/
2022-08-02 11:47:13,411 h5bench - INFO - Parallel setup: mpirun -np 8
2022-08-02 11:47:13,411 h5bench - ERROR - Unable to run the benchmark: 'MODE'
```

The `configuration.json` file is also available in the GitHub repo [here](https://github.com/hpc-io/h5bench/blob/master/configuration.json). 

Looking at its first `write` benchmark:
```json
{
    "benchmark": "write",
    "file": "test.h5",
    "configuration": {
        "MEM_PATTERN": "CONTIG",
        "FILE_PATTERN": "CONTIG",
        "NUM_PARTICLES": "16 M",
        "TIMESTEPS": "5",
        "DELAYED_CLOSE_TIMESTEPS": "2",
        "COLLECTIVE_DATA": "NO",
        "COLLECTIVE_METADATA": "NO",
        "EMULATED_COMPUTE_TIME_PER_TIMESTEP": "1 s", 
        "NUM_DIMS": "1",
        "DIM_1": "16777216",
        "DIM_2": "1",
        "DIM_3": "1",
        "ASYNC_MODE": "NON",
        "CSV_FILE": "output.csv"
    }
}
```
`ASYNC_MODE` is provided while `MODE` is missing. 

**2. Missing "mode" in the example configuration file (AMRex)**
Using the configuration.json file provided in [h5bench.readthedocs.io](https://h5bench.readthedocs.io/en/latest/amrex.html#json-configuration-recomended) returns the following error:
```shell
2022-08-02 12:04:36,003 h5bench - INFO - Starting h5bench Suite
2022-08-02 12:04:36,003 h5bench - WARNING - Base directory already exists: output
2022-08-02 12:04:36,003 h5bench - INFO - Lustre support not detected
2022-08-02 12:04:36,004 h5bench - INFO - h5bench [amrex] - Starting
2022-08-02 12:04:36,004 h5bench - INFO - h5bench [amrex] - DIR: output/a8b627f0/
2022-08-02 12:04:36,004 h5bench - INFO - Parallel setup: mpirun -np 8
2022-08-02 12:04:36,004 h5bench - ERROR - Unable to run the benchmark: 'mode'
```
The `configuration.json` file:
```json
{
    "benchmark": "amrex",
    "file": "amrex.h5",
    "configuration": {
        "ncells": "64",
        "max_grid_size": "8",
        "nlevs": "1",
        "ncomp": "6",
        "nppc": "2",
        "nplotfile": "2",
        "nparticlefile": "2",
        "sleeptime": "2",
        "restart_check": "1",
        "hdf5compression": "ZFP_ACCURACY#0.001"
    }
}
```
`mode` is missing.

Also, not sure if it's important but there's a mismatch between `mode` and `MODE` (lowercase vs uppercase).

**Software Environment**

 - version of h5bench: 1.3.0, (current master branch)
 - installed h5bench using: from source
 - operating system: 5.10.133-1-MANJARO
 - machine: PC
 - version of HDF5: 1.13.0
 - version of VOL-ASYNC: N/A
 - name and version of MPI: MPICH 4.0.2

### PR DESCRIPTION
**Pull request by jeanbez**
Update sample and documentation to reflect latest changes. Also fixes some issues raised in CI with HDF5 develop version related to H5VL_CAP_FLAG_ASYNC.

### CODE REVIEW

File: commons/h5bench_util.c [hunk 1]
```diff
@@ -67,13 +67,12 @@ h5bench_sleep(duration sleep_time)
...
 void
-async_sleep(hid_t file_id, hid_t fapl, duration sleep_time)
+async_sleep(hid_t es_id, duration sleep_time)
 {
 #ifdef USE_ASYNC_VOL
-    unsigned cap = 0;
-    H5Pget_vol_cap_flags(fapl, &cap);
-    if (H5VL_CAP_FLAG_ASYNC & cap)
-        H5Fstart(file_id, fapl);
+    int num_in_progress, op_failed;
```
Comment (houjun) [inline commons/h5bench_util.c:73]: size_t  num_in_progress;
hbool_t op_failed;

Comment (jeanbez) [reply commons/h5bench_util.c]: Thanks for catching that!

**Review by houjun — APPROVED** [review]
